// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testentitycachemodule.proxies;

public class ExampleSettings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject exampleSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestEntityCacheModule.ExampleSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GlobalExampleSetting("GlobalExampleSetting");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ExampleSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestEntityCacheModule.ExampleSettings"));
	}

	protected ExampleSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject exampleSettingsMendixObject)
	{
		if (exampleSettingsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestEntityCacheModule.ExampleSettings", exampleSettingsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestEntityCacheModule.ExampleSettings");

		this.exampleSettingsMendixObject = exampleSettingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ExampleSettings.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testentitycachemodule.proxies.ExampleSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testentitycachemodule.proxies.ExampleSettings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testentitycachemodule.proxies.ExampleSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testentitycachemodule.proxies.ExampleSettings(context, mendixObject);
	}

	public static testentitycachemodule.proxies.ExampleSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testentitycachemodule.proxies.ExampleSettings.initialize(context, mendixObject);
	}

	public static java.util.List<testentitycachemodule.proxies.ExampleSettings> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testentitycachemodule.proxies.ExampleSettings> result = new java.util.ArrayList<testentitycachemodule.proxies.ExampleSettings>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestEntityCacheModule.ExampleSettings" + xpathConstraint))
			result.add(testentitycachemodule.proxies.ExampleSettings.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of GlobalExampleSetting
	 */
	public final java.lang.String getGlobalExampleSetting()
	{
		return getGlobalExampleSetting(getContext());
	}

	/**
	 * @param context
	 * @return value of GlobalExampleSetting
	 */
	public final java.lang.String getGlobalExampleSetting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GlobalExampleSetting.toString());
	}

	/**
	 * Set value of GlobalExampleSetting
	 * @param globalexamplesetting
	 */
	public final void setGlobalExampleSetting(java.lang.String globalexamplesetting)
	{
		setGlobalExampleSetting(getContext(), globalexamplesetting);
	}

	/**
	 * Set value of GlobalExampleSetting
	 * @param context
	 * @param globalexamplesetting
	 */
	public final void setGlobalExampleSetting(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String globalexamplesetting)
	{
		getMendixObject().setValue(context, MemberNames.GlobalExampleSetting.toString(), globalexamplesetting);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return exampleSettingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testentitycachemodule.proxies.ExampleSettings that = (testentitycachemodule.proxies.ExampleSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestEntityCacheModule.ExampleSettings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
